import { StyleSheet, Dimensions} from "react-native";

export const CartScreenStyles = StyleSheet.create({
  backgroundContainer: {
    flex: 1,
    backgroundColor: '#221e27',
    alignItems: 'center',
  },
  container: {
    flex: 1,
    backgroundColor: '#221e27',
    maxWidth: 600,
    width: '100%',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#6C757D',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#221e27',
    borderBottomWidth: 1,
    borderBottomColor: '#221e27',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#f8fcffff',
  },
  itemCount: {
    fontSize: 14,
    color: '#f5faffff',
  },
  listContainer: {
    paddingVertical: 8,
  },
  emptyListContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyContainer: {
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#f0f7ffff',
    marginBottom: 12,
    textAlign: 'center',
  },
  emptyDescription: {
    fontSize: 16,
    color: '#ebeff1ff',
    textAlign: 'center',
    lineHeight: 24,
  },
  cartItem: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginVertical: 4,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  productImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#F8F9FA',
  },
  productInfo: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'space-between',
  },
  productTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 4,
  },
  productPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0bdf04ff',
    marginBottom: 8,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  quantityButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E9ECEF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#495057',
  },
  disabledText: {
    color: '#ADB5BD',
  },
  quantityText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212529',
    marginHorizontal: 16,
    minWidth: 20,
    textAlign: 'center',
  },
  removeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#DC3545',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  removeButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  checkoutSection: {
    backgroundColor: '#221e27',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#221e27',
  },
  totalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: '#f1f7fdff',
  },
  totalAmount: {
    fontSize: 24,
    fontWeight: '700',
    color: '#0bdf04ff',
  },
  checkoutButton: {
    backgroundColor: '#c725f8ff',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  checkoutButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
});

export const FeedScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#221e27',
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#221e27',
    borderBottomWidth: 1,
    borderBottomColor: '#333',
    zIndex: 1000,
    elevation: 10,
    position: 'relative',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flex: 1,
  },

  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#e1ecf8ff',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 16,
    color: '#d7dce0ff',
  },

  skippedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#08f88c',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  skippedButtonIcon: {
    fontSize: 16,
    color: '#221e27',
    fontWeight: 'bold',
    marginRight: 6,
  },
  skippedButtonText: {
    fontSize: 12,
    color: '#221e27',
    fontWeight: '600',
  },
  cardsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
    maxWidth: 600,
    width: '100%',
    alignSelf: 'center',
  },
  cardWrapper: {
    position: 'absolute',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 18,
    color: '#d6e4d8ff',
    textAlign: 'center',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#d8dfe7ff',
    marginBottom: 12,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 16,
    color: '#a9b1b8ff',
    textAlign: 'center',
    lineHeight: 24,
  },
  allDoneContainer: {
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  allDoneTitle: {
    fontSize: 32,
    marginBottom: 16,
  },
  allDoneSubtitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#d5dee7ff',
    marginBottom: 8,
    textAlign: 'center',
  },
  allDoneAction: {
    fontSize: 16,
    color: '#a1b1c0ff',
    textAlign: 'center',
  },
  refreshScrollView: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: -1,
  },
  refreshContainer: {
    flex: 1,
  },
  refreshHint: {
    position: 'absolute',
    bottom: 40,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  refreshHintText: {
    fontSize: 14,
    color: '#ADB5BD',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '70%',
    minHeight: 300,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E9ECEF',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#212529',
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseButtonText: {
    fontSize: 16,
    color: '#6C757D',
    fontWeight: 'bold',
  },
  modalEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  modalEmptyText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 8,
    textAlign: 'center',
  },
  modalEmptySubtext: {
    fontSize: 14,
    color: '#6C757D',
    textAlign: 'center',
    lineHeight: 20,
  },
  categoriesList: {
    flex: 1,
  },
  categoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F8F9FA',
  },
  categoryInfo: {
    flex: 1,
  },
  categoryName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 4,
  },
  categoryCount: {
    fontSize: 14,
    color: '#6C757D',
  },
  categoryChevron: {
    fontSize: 20,
    color: '#6C757D',
  },
});

export const SimpleProductDetailStyles = StyleSheet.create({
  modalBackground: {
    flex: 1,
    backgroundColor: '#221e27',
    alignItems: 'center',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#221e27',
    maxWidth: 600,
    width: '100%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#221e27',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  headerSpacer: {
    width: 32,
  },
  content: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#666666',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  errorText: {
    fontSize: 16,
    color: '#F44336',
    textAlign: 'center',
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: '#1976D2',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  retryButtonDisabled: {
    backgroundColor: '#BDBDBD',
    opacity: 0.6,
  },
  retryCountText: {
    fontSize: 12,
    color: '#b6b5b5ff',
    marginTop: 8,
    textAlign: 'center',
  },
  productInfo: {
    padding: 20,
  },
  productTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#f3ededff',
    marginBottom: 8,
    lineHeight: 32,
  },
  productPrice: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1fa726ff',
    marginBottom: 8,
  },
  productCategory: {
    fontSize: 16,
    color: '#afaeaeff',
    marginBottom: 16,
    textTransform: 'capitalize',
  },
  outOfStock: {
    fontSize: 14,
    color: '#F44336',
    fontWeight: '600',
    textTransform: 'uppercase',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#f7f1f1ff',
    marginTop: 24,
    marginBottom: 12,
  },
  productDescription: {
    fontSize: 16,
    color: '#f5ebebff',
    lineHeight: 24,
    marginBottom: 16,
  },
  specificationsContainer: {
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
  },
  specificationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E9ECEF',
  },
  specificationKey: {
    fontSize: 14,
    color: '#495057',
    fontWeight: '500',
    flex: 1,
  },
  specificationValue: {
    fontSize: 14,
    color: '#333333',
    fontWeight: '400',
    flex: 1,
    textAlign: 'right',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingBottom: 20,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  actionButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skipButton: {
    backgroundColor: '#FFEBEE',
    borderWidth: 1,
    borderColor: '#c725f8ff',
  },
  skipButtonText: {
    color: '#b91decff',
    fontWeight: '600',
    fontSize: 16,
  },
  cartButton: {
    backgroundColor: '#08f88c',
  },
  cartButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  likeButton: {
    backgroundColor: '#c725f8ff',
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  likeButtonText: {
    color: '#f1fcf1ff',
    fontWeight: '600',
    fontSize: 16,
  },
});

export const SkippedProductStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#221e27',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#221e27',
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    fontSize: 20,
    color: '#08f88c',
    fontWeight: 'bold',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#e1ecf8ff',
    textAlign: 'center',
    flex: 1,
  },
  clearButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#dc3545',
    borderRadius: 8,
  },
  clearButtonText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  headerSpacer: {
    width: 40,
  },
  subtitle: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#221e27',
    alignItems: 'center',
  },
  subtitleText: {
    fontSize: 16,
    color: '#d7dce0ff',
    marginBottom: 4,
  },
  instructionText: {
    fontSize: 14,
    color: '#a9b1b8ff',
    textAlign: 'center',
  },
  cardsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  cardWrapper: {
    position: 'absolute',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 18,
    color: '#d6e4d8ff',
    textAlign: 'center',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#d8dfe7ff',
    marginBottom: 12,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 16,
    color: '#a9b1b8ff',
    textAlign: 'center',
    lineHeight: 24,
  },
  allDoneContainer: {
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  allDoneTitle: {
    fontSize: 32,
    marginBottom: 16,
  },
  allDoneSubtitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#d5dee7ff',
    marginBottom: 24,
    textAlign: 'center',
  },
  backToFeedButton: {
    backgroundColor: '#08f88c',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 32,
  },
  backToFeedButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#221e27',
  },
});

const { width } = Dimensions.get('window');
const ITEM_WIDTH = (width - 48) / 2; // 2 columns with margins

export const WishListStyles = StyleSheet.create({
  backgroundContainer: {
    flex: 1,
    backgroundColor: '#221e27',
    alignItems: 'center',
  },
  container: {
    flex: 1,
    backgroundColor: '#221e27',
    maxWidth: 600,
    width: '100%',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#6C757D',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#221e27',
    borderBottomWidth: 1,
    borderBottomColor: '#221e27',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#f6f9fdff',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemCount: {
    fontSize: 14,
    color: '#eaf0f5ff',
    marginRight: 12,
  },
  viewModeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E9ECEF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewModeButtonText: {
    fontSize: 16,
    color: '#d3d9dfff',
  },
  listContainer: {
    paddingVertical: 8,
  },
  emptyListContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyContainer: {
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#f4faffff',
    marginBottom: 12,
    textAlign: 'center',
  },
  emptyDescription: {
    fontSize: 16,
    color: '#d9e0e6ff',
    textAlign: 'center',
    lineHeight: 24,
  },
  // Grid view styles
  gridItem: {
    width: ITEM_WIDTH,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    margin: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  gridImage: {
    width: '100%',
    height: ITEM_WIDTH * 0.8,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    backgroundColor: '#F8F9FA',
  },
  gridItemInfo: {
    padding: 12,
  },
  gridItemTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 4,
    height: 36,
  },
  gridItemPrice: {
    fontSize: 16,
    fontWeight: '700',
    color: '#007BFF',
    marginBottom: 8,
  },
  gridItemActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addToCartButton: {
    flex: 1,
    backgroundColor: '#08f88c',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 8,
  },
  addToCartButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  removeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#DC3545',
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeButtonText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  // List view styles
  listItem: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginVertical: 4,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  listImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#F8F9FA',
  },
  listItemInfo: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'space-between',
  },
  listItemTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 4,
  },
  listItemPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: '#00ff15ff',
    marginBottom: 4,
  },
  addedDate: {
    fontSize: 12,
    color: '#6C757D',
  },
  listItemActions: {
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  listAddToCartButton: {
    backgroundColor: '#007BFF',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  listAddToCartButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  listRemoveButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#DC3545',
    justifyContent: 'center',
    alignItems: 'center',
  },
});